-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 14:57:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mesajil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mesajil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mesajil` DEFAULT CHARACTER SET utf8 ;
USE `db_mesajil` ;

-- -----------------------------------------------------
-- Table `db_mesajil`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` VARCHAR(200) NULL,
  `fechaRegistro` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_rol_idx` (`idRol` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `db_mesajil`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `fechaRegistro` DATETIME NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` TEXT NULL,
  `marca` VARCHAR(80) NOT NULL,
  `modelo` VARCHAR(80) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `fechaRegistro` DATETIME NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_producto_categoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `db_mesajil`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCarrito`),
  INDEX `fk_producto_rol_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_mesajil`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`DetalleCarrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`DetalleCarrito` (
  `idDetalleCarrito` INT NOT NULL AUTO_INCREMENT,
  `idCarrito` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precioUnitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idDetalleCarrito`),
  INDEX `fk_carrito_rol_idx` (`idCarrito` ASC) VISIBLE,
  INDEX `fk_detallecarrito_producto_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_detallecarrito_carrito`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `db_mesajil`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallecarrito_producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_mesajil`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `estadoPedido` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_usuario_rol_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_mesajil`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precioUnitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_pedido_rol_idx` (`idPedido` ASC) VISIBLE,
  INDEX `fk_producto_rol_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_detallepedido_pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `db_mesajil`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallepedido_producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_mesajil`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`ImagenesProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`ImagenesProducto` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `urlImagen` VARCHAR(255) NOT NULL,
  `principal` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idImagen`),
  INDEX `fk_producto_rol_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_imagen_producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_mesajil`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mesajil`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mesajil`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `stockActual` INT NOT NULL DEFAULT 0,
  `stockMinimo` INT NOT NULL DEFAULT 0,
  `ultimaActualizacion` DATETIME NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_producto_rol_idx` (`idProducto` ASC) VISIBLE,
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_mesajil`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
